;(() => {
	var initStr = Loader.prototype.init.toString()
	initStr = initStr.slice(initStr.indexOf("{") + 1, initStr.lastIndexOf("}"))
	initStr = initStr.replace('"api/config"', '"api/config.json"')
	Loader.prototype.init = Function("callback", initStr)
	
	var runStr = Loader.prototype.run.toString()
	runStr = runStr.slice(runStr.indexOf("{") + 1, runStr.lastIndexOf("}"))
	runStr = runStr.replace('"api/categories"', '"api/categories.json"')
	runStr = runStr.replace('ajax("api/songs"', 'ajax("api/songs.json"')
	runStr = runStr.replace(' + "fonts/"', ' + (gameConfig.assets_no_dir ? "" : "fonts/")')
	runStr = runStr.replaceAll(' + "img/"', ' + (gameConfig.assets_no_dir ? "" : "img/")')
	runStr = runStr.replace(' + "img/vectors.json"', ' + (gameConfig.assets_no_dir ? "vectors.json" : "img/vectors.json")')
	runStr = runStr.replace('song.id + "/"', 'song.id + (gameConfig.assets_no_dir ? "" : "/")')
	runStr = runStr.replace('directory + "main."', 'directory + (gameConfig.assets_no_dir ? "." : "main.")')
	Loader.prototype.run = Function(runStr)
})()
